### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by BorisKourt** [zyedidia/Literate#3]
I am new to D but don't mind looking into helping out with this tool. Do you have any advice on getting started? 

Not sure if this is implemented but one of the features from Org/Babel/noweb is indicating whether a block will be included in the weave or not (i.e. for Leaving repetitive code out of the HTML export) 

If this isn't implemented I can take a look at getting it in.

**Comment by zyedidia** [comment]
Great! D is a really good language in my opinion. If you're interested in learning D you can check out [dlang.org](https://dlang.org). There is also [Programming in D](http://ddili.org/ders/d.en/index.html) which is an online book. It's basically a bunch of tutorials covering different aspects of D.

In terms of this project, the code is written in literate D in the `dsrc` directory. You can build the code by running `make debug` from the top level (use `make release` or `make` to build with optimizations). Hopefully the code isn't too hard to understand -- I've tried to explain it well, although `weaver.lit` is a mess right now.

The feature you mentioned is not currently implemented, but it might not be so easy to implement. I'm not sure what the weaver should do when a "hidden" codeblock is used because it won't be able to link it. Maybe there should be some indication that it's a hidden codeblock? Also I don't know what the syntax should be to indicate that a certain codeblock shouldn't be included in the weave.

Something very simple to implement would be to add simple single line comments. So if a line starts with `//` it should be ignored (except if the line is in a codeblock). Leading whitespace also shouldn't matter so these are both valid comments:
```
// this is a comment
     // this is a comment
```

I would suggest adding the code at line 290 of `dsrc/parser.lit`. You can use the `inCodeblock` boolean to check if the current line is in a codeblock. To remove the leading whitespace you can use the `strip` function, and then you can check the beginning of the line with the `startsWith` function. Once you've determined that the line is a comment and should be skipped, you can use `continue` to move on to the next iteration of the loop.

**Comment by BorisKourt** [comment]
Thanks for the detailed introduction!

We could take the convention from org babel, and add another modifier like your `+=`.

```
--- Block name --no-weave
// Do tangle this if referenced. 
// But don't display this block in html.
---
```
The syntax could be whatever you think makes the most sense.

Here are some examples for the org 'modifiers':
Base:
```org
#+BEGIN_SRC clojure
;; Code
#+END_SRC
```
Don't export:
```org
#+BEGIN_SRC clojure :exports none
;; Code
#+END_SRC
```
Tangle with file, and use in noweb.
```org
#+BEGIN_SRC clojure :tangle project.clj :noweb yes
;; Code
#+END_SRC
```

**Comment by zyedidia** [comment]
Ok, that seems fine. Maybe there should be a list of flags (things in the name that start with `--`?) in the `Block` class so it's easy to add other options if necessary.

And if another block uses a hidden block, it just won't display a link for it:

```
@{normal_block, 1}
@{hidden_block}
```

**Comment by BorisKourt** [comment]
Yup, I've started down that route. Will share the code today. I think I am getting the hang of the codebase, just doing a lot of searching for D conventions.

**Comment by zyedidia** [comment]
By the way, I recently pushed a commit that adds some more explanation to the weaver. Hopefully that might be useful.

**Comment by zyedidia** [comment]
With #4 merged, I think we can close this issue.
