### ISSUE TITLE
Syntax highlighting in HTML output broken for Scheme/Lisp

### ISSUE THREAD

**Issue by sobjornstad** [zyedidia/Literate#6]
It's barely detecting *anything* correctly, as shown below (not even comments). I'd much rather have no syntax highlighting at all than this garbage output (there doesn't appear to be an option for this?). The `lang-scheme` part is landing in the pre tag correctly, but the prettify code seems to be interpreting it incorrectly. The highlighting in vim is correct (I declared `@code_type scheme .scm`). I also tried `lisp` to no effect (except making the vim highlighting slightly worse).

![syntax](https://cloud.githubusercontent.com/assets/2313414/13413283/ffe4f3f2-df0e-11e5-99c0-751d1a1211b9.png)

*Whoops, I misspelled 'these' in the screenshot, but I'm not going to go take it again just for that...*

**Comment by zyedidia** [comment]
There are a couple things you can do to fix this. The syntax highlighting engine used by Literate is [prettify.js](https://github.com/google/code-prettify). There are a number of languages that are supported via extensions (of which Lisp/Scheme is one) but they need to have an extra javascript file included. This is simple enough by adding the following line to the first section (or any other section):

```html
<script src="https://raw.githubusercontent.com/google/code-prettify/master/src/lang-lisp.js"></script>
```
If you do this though, you need to set the `code_type` to lisp (it would be good if the `code_type` and the `lang-...` were defined separately because sometimes they are different: `scheme` for vim and `lang-scm` for prettify).

(I realized that the vim highlighting for comments `//` was broken -- if you update the plugin it should be fixed).

You can also paste the [javascript](https://raw.githubusercontent.com/google/code-prettify/master/src/lang-lisp.js) directly in if you'd like so that the html file will also work offline. 

The second option is to disable the syntax highlighting completely. You can do this by adding the following line to the top of the file:

```
@colorscheme /dev/null
```
I realize this isn't the nicest solution, I'll work on either adding a flag to or a command (such as `@no_colorscheme`) disable syntax highlighting.

**Comment by sobjornstad** [comment]
Thanks for the quick response! That works great.

**Comment by zyedidia** [comment]
I've just made another commit so that Literate will automatically include the javascript, so you can basically disregard the whole `<script src=`... part. Just pull the latest version of Literate (or clone a new version), run make, and everything should work fine.
